# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gomall?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


